<?php

/**
 * @file
 * Contains moderation_state_columns.module.
 */

use Drupal\Component\Utility\SortArray;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\workflows\Entity\Workflow;

/**
 * Implements hook_help().
 */
function moderation_state_columns_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the moderation_state_columns module.
    case 'help.page.moderation_state_columns':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a view display that shows moderation states as columns.') . '</p>';
      return $output;
  }
}

/**
 * Preprocess hook for the moderation_state_columns views style.
 */
function template_preprocess_views_view_moderation_state_columns(&$variables) {
  $entities = [];
  $states = [];
  /** @var \Drupal\content_moderation\ModerationInformationInterface $moderationInformation */
  $moderationInformation = \Drupal::service('content_moderation.moderation_information');
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $variables['view'];
  /** @var \Drupal\workflows\Entity\Workflow $workflow */
  $workflow = Workflow::load($view->style_plugin->options['workflow']);

  $stateDefinitions = $workflow->get('type_settings')['states'];
  uasort($stateDefinitions, 'Drupal\Component\Utility\SortArray::sortByWeightElement');
  foreach ($stateDefinitions as $id => $state) {
    $states[$id] = $state['label'];
  }

  if (!isset($variables['#cache']['tags'])) {
    $variables['#cache']['tags'] = [];
  }
  $variables['#cache']['tags'] = array_merge($variables['#cache']['tags'], $workflow->getCacheTags());

  foreach ($variables['rows'] as $row) {
    $entity = NULL;
    foreach ($row as $item) {
      if ($item instanceof EntityInterface && $moderationInformation->isModeratedEntity($item)) {
        $entity = $item;
      }
    }
    if (!$entity) {
      // No moderated entity found in the results. Ignore this row.
      continue;
    }
    $variables['#cache']['tags'] = array_merge($variables['#cache']['tags'], $entity->getCacheTags());
    $state = $entity->get('moderation_state')->value;
    $entities[$state][] = render($row);
  }

  $variables['json_encoded_content'] = json_encode([
    'states' => $states,
    'entities' => $entities,
  ]);

  $variables['#attached']['library'][] =  'moderation_state_columns/view_display';
}
