<?php

/**
 * @file
 * Contains moderation_state_columns.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\workflows\Entity\Workflow;

/**
 * Implements hook_help().
 */
function moderation_state_columns_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the moderation_state_columns module.
    case 'help.page.moderation_state_columns':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a view display that shows moderation states as columns.') . '</p>';
      return $output;
  }
}

/**
 * Preprocess hook for the moderation_state_columns views style.
 */
function template_preprocess_views_view_moderation_state_columns(&$variables) {
  // TODO: Make it work with ajax views.

  $states = [];
  $entities = [];
  /** @var \Drupal\content_moderation\ModerationInformationInterface $moderationInformation */
  $moderationInformation = \Drupal::service('content_moderation.moderation_information');
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $variables['view'];
  $options = $view->style_plugin->options;
  /** @var \Drupal\workflows\Entity\Workflow $workflow */
  $workflow = Workflow::load($options['workflow']);

  foreach ($workflow->get('type_settings')['states'] as $id => $state) {
    $states[$id] = $state['label'];
  }

  foreach ($variables['rows'] as $row) {
    $entity = NULL;
    foreach ($row as $item) {
      if ($item instanceof EntityInterface && $moderationInformation->isModeratedEntity($item)) {
        $entity = $item;
      }
    }
    if (!$entity) {
      // No moderated entity found in the results. Ignore this row.
      continue;
    }
    $state = $entity->get('moderation_state')->value;
    $entities[$state][] = render($row);
  }

  // Update options for twig.
  $variables['#attached']['drupalSettings']['moderationStateColumns'][$view->dom_id] = [
    'states' => $states,
    'entities' => $entities,
  ];
  $variables['#attached']['library'][] =  'moderation_state_columns/view_display';
}
